export const CHANGE_USERNAME = "CHANGE_USERNAME";
export const CHANGE_STOP_SMOKING_DATE = "CHANGE_STOP_SMOKING_DATE";
export const CHANGE_CIGARETTES_PER_DAY = "CHANGE_CIGARETTES_PER_DAY";
export const CHANGE_CIGARETTES_PER_PACK = "CHANGE_CIGARETTES_PER_PACK";
export const CHANGE_CIGARETTE_BRAND = "CHANGE_CIGARETTE_BRAND";
export const CHANGE_PRICE_PER_PACK = "CHANGE_PRICE_PER_PACK";